# グローバル設定
command_timeout = 1000  # 1秒に設定（デフォルトは500ms）

[os]
format = "[$symbol](bold white)"
disabled = false
[os.symbols]
Macos = " " #リンゴのicon
Ubuntu = " " #Ubuntuのicon

[directory]
truncation_length = 5
truncation_symbol = ".../"
truncate_to_repo = false
read_only = " 󰌾" #鍵のicon

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

